- name: Install nginx and PHP 7 on localhost
  hosts: 127.0.0.1
  connection: local
  roles:
    - php70
    - webserver
    - mysql57

  vars:
    php_hosts:
    symfony_hosts:
      - {host: "quotes.dev", path: "src/"}