- name: install nginx
  apt: name=nginx state=present

- name: upstream PHP 7 config
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream-{{ item.host }}.conf
  with_items: "{{ symfony_hosts }}"
