- name: Add PHP7 PPA
  apt_repository: repo='ppa:ondrej/php-7.0'

- name: Install php7
  apt: name={{item}} state=present
  with_items:
    - php7.0
    - php7.0-fpm
    - php7.0-cli
    - php7.0-curl
    - php7.0-gd
    - php7.0-intl
    - php7.0-mysql
    - php7.0-opcache